# Generated by Django 5.0.6 on 2025-08-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PERSON', 'Persona'), ('COMPANY', 'Empresa')], default='PERSON', max_length=10)),
                ('name', models.CharField(max_length=150)),
                ('document_id', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customer',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='customer_name_364ac9_idx'), models.Index(fields=['document_id'], name='customer_documen_a085cd_idx')],
            },
        ),
    ]
