# Generated by Django 5.0.6 on 2025-08-25 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('IN_PROGRESS', 'En proceso'), ('DONE', 'Finalizada'), ('CANCELLED', 'Cancelada')], default='OPEN', max_length=12)),
                ('complaint', models.TextField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workorders', to='customers.customer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workorders', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'work_order',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.part')),
                ('workorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='workorders.workorder')),
            ],
            options={
                'db_table': 'work_order_part',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.service')),
                ('workorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='workorders.workorder')),
            ],
            options={
                'db_table': 'work_order_service',
            },
        ),
    ]
