# Generated by Django 5.0.6 on 2025-09-24 21:19

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_part_options_alter_service_options_and_more'),
        ('customers', '0002_alter_customer_options_and_more'),
        ('quotes', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.CheckConstraint(check=models.Q(('subtotal_services__gte', 0)), name='q_subtot_services_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.CheckConstraint(check=models.Q(('subtotal_parts__gte', 0)), name='q_subtot_parts_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.CheckConstraint(check=models.Q(('discount_total__gte', 0)), name='q_discount_total_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.CheckConstraint(check=models.Q(('tax_total__gte', 0)), name='q_tax_total_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.CheckConstraint(check=models.Q(('grand_total__gte', 0)), name='q_grand_total_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='quotationpart',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='qp_quantity_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='quotationpart',
            constraint=models.CheckConstraint(check=models.Q(('unit_price__gte', 0)), name='qp_unit_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='quotationpart',
            constraint=models.CheckConstraint(check=models.Q(('discount__gte', 0)), name='qp_discount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='quotationpart',
            constraint=models.CheckConstraint(check=models.Q(('discount__lte', django.db.models.expressions.CombinedExpression(models.F('quantity'), '*', models.F('unit_price')))), name='qp_discount_le_subtotal'),
        ),
        migrations.AddConstraint(
            model_name='quotationservice',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='qs_quantity_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='quotationservice',
            constraint=models.CheckConstraint(check=models.Q(('unit_price__gte', 0)), name='qs_unit_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='quotationservice',
            constraint=models.CheckConstraint(check=models.Q(('discount__gte', 0)), name='qs_discount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='quotationservice',
            constraint=models.CheckConstraint(check=models.Q(('discount__lte', django.db.models.expressions.CombinedExpression(models.F('quantity'), '*', models.F('unit_price')))), name='qs_discount_le_subtotal'),
        ),
    ]
